### ISSUE TITLE
Getting 400 response

### ISSUE THREAD

**Issue by jasondemeter** [marcus-crane/october#10]
Thanks for this project, it seems perfect for my needs! Unfortunately I'm getting a 400 response when I attempt to sync. Tested both the universal and amd MacOS releases.

![image](https://user-images.githubusercontent.com/33297457/152691643-49d60e2d-516e-403e-9873-a70e09febbdb.png)

**Comment by marcus-crane** [comment]
Hey there,

First off, thanks for giving October a spin. There isn't currently any logging being saved so I have no way to know (on my end) what went wrong here but I'll release an update shortly so you can either have a look for yourself or share the logs with me so I can try to see what's up.

Thanks!

**Comment by marcus-crane** [comment]
Hey @jasondemeter,

I've just released `v0.9.2` which puts some proper logging in the app and will save them to a log file.

If you can upgrade and then run through attempting an upload again, it'll save the response from Readwise to the log file which you can upload here.

You can find the location of the log files [here](https://github.com/marcus-crane). Feel free to reach out if you need some pointers on how to navigate to those files though.

The logs don't contain any sensitive information (eg; Readwise token) but if you prefer to not share them publically, feel free to forward them to october@utf9k.net and I'll get back to you shortly.

Thankfully I'm also in the Readwise Discord so if needed, I can bug the devs to see what's up with the API but odds are it'll be something to do with the bookmarks being parsed being malformed or something.

**Comment by jasondemeter** [comment]
Hi Marcus, 
I've sent over the log file. Each one of my highlights got a `Bookmark has no source title so skipping to next item` error message, thus no payload was sent to the Readwise API. I just got my Libra 2 so I have only 43 highlights across 2 books, both of which were side-loaded with Calibre. I think the fact that they're side-loaded may be part of the issue here. Let me know if there is any other experimentation you'd like me to do — I'll get back quicker next time!
Thanks!

**Comment by marcus-crane** [comment]
@jasondemeter Ah, thanks for sending that through!

I personally use sideloaded books myself and it's what October is primarily developed against. That said, I use [Calibre](https://calibre-ebook.com/) to add metadata to items before sending them over to my Kobo.

What I can do in this case is just set the title to be the epub name so eg; `Vagabonding - Rolf Potts.epub` and then you can edit it in Readwise if you prefer.

The bare minimum needed really is just a highlight and a title though. I'll see about pushing an update shortly and thanks again for the log file 🙂

**Comment by marcus-crane** [comment]
Hey @jasondemeter,

I've just released a new version of October that should allow you to upload items now. In short, if no title is present, October will use the filename instead. If that somehow doesn't work (it should be impossible...), it'll just send the highlights off with no title. Readwise will then create a book simply called "Quotes".

Thanks again for bringing this issue to my attention and let me know how you get on with the update :)

![CleanShot 2022-02-12 at 19 29 16](https://user-images.githubusercontent.com/14816406/153700309-613f847c-6d71-4c04-b2e6-fbac55161516.png)
![CleanShot 2022-02-12 at 19 28 36](https://user-images.githubusercontent.com/14816406/153700310-3f385f2c-671c-4adb-b909-2d76d4e64c61.png)

**Comment by marcus-crane** [comment]
Oh interesting? 🤔 Any chance you could send me the epub file so I can see about recreating it? I don't imagine it's specific to the file. It did occur to me that all of my books are actually kepubs, using the kobo epub plugin.

While I don't know the specifics on what differs, perhaps that makes a difference in how metadata is loaded into the Kobo database?

Another possible fallback could be trying to extract the metadata from the epub itself. Given they're just zipped up HTML, it shouldn't be too expensive to poke inside and look for a metadata title tag

**Comment by marcus-crane** [comment]
Ah and thanks for pointing out the oversight in the About section 😅

**Comment by marcus-crane** [comment]
Anyway, I'll close this issue for now but feel free to reply here. I've also captured the topics mentioned as standalone tasks.
