### ISSUE TITLE
error october import hightlights from kobo

### ISSUE THREAD

**Issue by gertjanstoker** [marcus-crane/october#123]
I have an issue with...

---

<details><summary>System Details</summary><ul><li>Version: v1.8.0</li><li>Platform: darwin</li><li>Architecture: amd64</li></details>

**Comment by marcus-crane** [comment]
Hi there,

Unfortunately I can't provide any assistance without knowing more about what kind of issues you're running into so I'm going to close this issue but feel free to submit another with more information such as what error message you're seeing for example.
