### ISSUE TITLE
Generate a NSIS Installer for Windows

### ISSUE THREAD

**Issue by marcus-crane** [marcus-crane/october#20]
For WIndows, using a standalone exe is weird and not really how to distribute things "professionally"

Instead, we need to create an installer and generate a start menu entry to make October as handy to end users as possible.

This is a task for down the line however since at the moment, I don't even think Windows builds work

**Comment by leaanthony** [comment]
This is literally happening right now 👍

**Comment by marcus-crane** [comment]
@leaanthony Very cool stuff! I'm now distributing an NSIS installer :)
