### ISSUE TITLE
Extra title fallback by checking epub meta tags

### ISSUE THREAD

**Issue by marcus-crane** [marcus-crane/october#28]
For cases where an epub doesn't have a title, I should see how expensive it is to extract information from the metatags inside the epub archive itself.

It may be that if epubs don't have DB metadata present, that this path is used heavily so the cost needs to be assessed

**Comment by marcus-crane** [comment]
Re: #10

**Comment by jasondemeter** [comment]
I did a test with [The Great Gatsby epub from Project Gutenberg](https://www.gutenberg.org/ebooks/64317) and despite the metadata appearing correctly in Calibre and Kobo, October couldn't find it. Would be interesting to see if you can reproduce the error.
```
{"level":"info","ts":1644854572.448309,"caller":"october/app.go:81","msg":"Starting up October"}
{"level":"info","ts":1644854583.619997,"caller":"october/kobo_service.go:213","msg":"Found a Kobo Libra 2 through fallback method"}
{"level":"info","ts":1644854583.62533,"caller":"october/kobo_service.go:213","msg":"Found a Kobo Libra 2 through fallback method"}
{"level":"info","ts":1644854586.0902212,"caller":"october/kobo_service.go:252","msg":"User has selected Kobo Libra 2","kobo":{"name":"Kobo Libra 2","storage":32,"display_ppi":300,"mnt_path":"/Volumes/KOBOeReader","db_path":"/Volumes/KOBOeReader/.kobo/KoboReader.sqlite"}}
{"level":"info","ts":1644854586.1288881,"caller":"october/kobo_service.go:259","msg":"Successfully opened connection to /Volumes/KOBOeReader/.kobo/KoboReader.sqlite"}
{"level":"info","ts":1644854588.963125,"caller":"october/kobo_service.go:354","msg":"Starting to build Readwise payload out of 57 bookmarks"}
{"level":"error","ts":1644854588.963386,"caller":"october/kobo_service.go:379","msg":"No title. Fallback of using filename failed. Not required so will send with no title.","source":{"ContentID":"","ContentType":"","MimeType":"","BookID":"","BookTitle":"","ImageId":"","Title":"Great Gatsby, The - F. Scott Fitzgerald","Attribution":"","Description":"","DateCreated":"","ShortCoverKey":"","AdobeLocation":"","Publisher":"","IsEncrypted":false,"DateLastRead":"","FirstTimeReading":false,"ChapterIDBookmarked":"","ParagraphBookmarked":0,"BookmarkWordOffset":0,"NumShortcovers":0,"VolumeIndex":0,"NumPages":0,"ReadStatus":0,"SyncTime":"","UserID":"","PublicationId":"","FileOffset":0,"FileSize":0,"PercentRead":"","ExpirationStatus":0,"FavouritesIndex":0,"Accessibility":0,"ContentURL":"","Language":"","BookshelfTags":"","IsDownloaded":false,"FeedbackType":0,"AverageRating":0,"Depth":0,"PageProgressDirection":"","InWishlist":"","ISBN":0,"WishlistedDate":"","FeedbackTypeSynced":false,"IsSocialEnabled":false,"EpubType":"","Monetization":"","ExternalId":"","Series":"","SeriesNumber":"","Subtitle":"","WordCount":"","Fallback":"","RestOfBookEstimate":"","CurrentChapterEstimate":"","CurrentChapterProgress":0,"PocketStatus":"","UnsyncedPocketChanges":"","ImageUrl":"","DateAdded":"","WorkId":"","Properties":"","RenditionSpread":"","RatingCount":"","ReviewsSyncDate":"","MediaOverlay":"","RedirectPreviewUrl":false,"PreviewFileSize":0,"EntitlementId":"","CrossRevisionId":"","DownloadUrl":false,"ReadStateSynced":false,"TimesStartedReading":0,"TimeSpentReading":0,"LastTimeStartedReading":"","LastTimeFinishedReading":"","ApplicableSubscriptions":"","ExternalIds":"","PurchaseRevisionId":"","SeriesID":"","SeriesNumberFloat":0,"AdobeLoanExpiration":"","HideFromHomePage":false,"IsInternetArchive":false,"TitleKana":"","SubtitleKana":"","SeriesKana":"","AttributionKana":"","PublisherKana":"","IsPurchaseable":false,"IsSupported":false,"AnnotationsSyncToken":"","DateModified":""},"bookmark":{"BookmarkID":"e0a2a5c9-3526-497f-a7b5-d05e9b41b6f6","VolumeID":"file:///mnt/onboard/Fitzgerald, F. Scott (Francis Scott)/Great Gatsby, The - F. Scott Fitzgerald.epub","ContentID":"file:///mnt/onboard/Fitzgerald, F. Scott (Francis Scott)/Great Gatsby, The - F. Scott Fitzgerald.epub#(10)OEBPS/4118475121438256323_64317-h-4.htm.html#chapter-9","StartContainerPath":"OEBPS/4118475121438256323_64317-h-4.htm.html#point(/1/4/3/321:1)","StartContainerChild":"","StartContainerChildIndex":"-99","StartOffset":"0","EndContainerPath":"OEBPS/4118475121438256323_64317-h-4.htm.html#point(/1/4/3/325:0)","EndContainerChildIndex":"-99","EndOffset":"0","Text":"Gatsby believed in the green light, the orgastic future that year by year recedes before us. It eluded us then, but that’s no matter—tomorrow we will run faster, stretch out our arms further… And one fine morning—\n So we beat on, boats against the current, borne back ceaselessly into the past.","Annotation":"","ExtraAnnotationData":"","DateCreated":"2022-02-14T16:02:39.239","ChapterProgress":0.9435483870967742,"Hidden":"false","Version":"","DateModified":"","Creator":"","UUID":"","UserID":"08e469e5-2240-42df-a56d-8d2013ea275a","SyncTime":"","Published":"false","ContextString":"","Type":"highlight"},"stacktrace":"main.(*KoboService).BuildReadwisePayload\n\t/Users/runner/work/october/october/kobo_service.go:379\nmain.(*KoboService).SendBookmarksToReadwise\n\t/Users/runner/work/october/october/kobo_service.go:417\nreflect.Value.call\n\t/Users/runner/hostedtoolcache/go/1.17.2/x64/src/reflect/value.go:543\nreflect.Value.Call\n\t/Users/runner/hostedtoolcache/go/1.17.2/x64/src/reflect/value.go:339\ngithub.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call\n\t/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/binding/boundMethod.go:73\ngithub.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage\n\t/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/dispatcher/calls.go:45\ngithub.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage\n\t/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/dispatcher/dispatcher.go:36\ngithub.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage.func1\n\t/Users/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.30/internal/frontend/desktop/darwin/frontend.go:248"}
{"level":"info","ts":1644854588.967703,"caller":"october/kobo_service.go:393","msg":"Successfully parsed 57 highlights"}
{"level":"info","ts":1644854590.165664,"caller":"october/kobo_service.go:437","msg":"Successfully sent 57 bookmarks to Readwise"}
```

**Comment by marcus-crane** [comment]
Weird, the VolumeID is definitely there 🤔 I'll have a look. Thanks for providing the epub

**Comment by marcus-crane** [comment]
Ah, that error shouldn't have been logged. It just happens I accidentally log that all the time

Instead it should be something like:

```bash
sourceFile, err := url.Parse(entry.VolumeID)
if err != nil {
  k.Logger.Errorw("No title. Fallback of using filename failed...")
  continue
}
filename := path.Base(sourceFile.Path)
k.Logger.Debugw(fmt.Sprintf("No source title. Constructing title from filename: %s", filename))
source.Title = strings.TrimSuffix(filename, ".epub")
```

Just to confirm, the book in Readwise didn't get renamed to "Great Gatsby, The - F. Scott Fitzgerald"?

I'll see if I can look into the issue this weekend

**Comment by jasondemeter** [comment]
I don't believe it was simply a logging error - it was added to Readwise as "Great Gatsby, The - F. Scott Fitzgerald" and thus far all Kobo/October books have been added using the filename fallback.

**Comment by jasondemeter** [comment]
I installed the KoboTouchExtended plugin for Calibre, which automatically converts epubs to kepubs when sending a book to Kobo, and this solved the metadata problem when exporting with October. Also, the UX when reading on the Kobo itself is greatly improved with kepub vs epub! So the problem is solved for me, and I wonder whether it's worth it to integrate thorough epub support in October, which is just not how one should be using a Kobo. Perhaps just a note in the README that only kepub is fully supported? Anyway, thanks for looking into this for me and for building October!

**Comment by marcus-crane** [comment]
Ah thanks for your insights 🙂 I haven't sat down to look at this yet but I'll do some digging into what gets populated into the DB for epub vs kepub. I still would have expected the file fallback to work 🤔

**Comment by marcus-crane** [comment]
> I don't believe it was simply a logging error - it was added to Readwise as "Great Gatsby, The - F. Scott Fitzgerald" and thus far all Kobo/October books have been added using the filename fallback.

Ah! I misunderstood this when I first skimmed it. I thought the fallback still wasn't working (despite the log message appearing being a bug) which didn't seem possible but as I understand it, it did work but obviously isn't ideal compared to using Kepubs.

I definitely think kepubs are the way to go, and I use them myself. It probably makes sense to populate a little info notice to the user recommending kepubs but I think just having the filename in Readwise for epubs is fine as a starting point.

Anyway, given the fallback is apparently working, I'll close this issue but as always, feel free to open a new one (or rely to this one) if you need anything

**Comment by marcus-crane** [comment]
@jasondemeter 🤦  The database query I had been using was locked to epubs: https://github.com/marcus-crane/october/blob/459d27a0c9b92f7c6b71292b25c5f1683b637c9f/kobo_service.go#L302

It would have been using the fallback method for kepubs, given the database query returns no results and as a result, just uses the data constructed from the filename, which is saved with the bookmark

I've removed that limitation in #31 among other tidying up. By the way, as the only user I'm aware of, when I enable uploading with covers, you'll end up with one-time duplicates as I now add the epub filepath (on your Kobo) as a "source URL. Upon bookmarks uploading successfully, I intend to then upload covers that are populated via Calibre (if one hasn't already been set in the Readwise UI).
