### ISSUE TITLE
Binary was compiled with 'CGO_ENABLED=0' error

### ISSUE THREAD

**Issue by manikoutai** [marcus-crane/october#40]
Hi,
 after installing October on my windows 10 machine, I am able to start it and it can see my Kobo. Meanwhile, when I click on it, I receive an error saying : 

 Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work.  This is a stub.

What am I missing?

**Comment by marcus-crane** [comment]
Ah ok, I guess I need to explicitly enable CGO. I haven't done extensive testing on Windows for a while but I'll release a new version shortly to fix this up. I personally use the macOS version and test the Windows version in a VM but I haven't done that in a little while.

**Comment by leaanthony** [comment]
@marcus-crane - You could always try https://pkg.go.dev/modernc.org/sqlite

**Comment by marcus-crane** [comment]
@leaanthony Ah, thanks! I'll have a look into it 🙂
