### ISSUE TITLE
Import error: parsing time

### ISSUE THREAD

**Issue by jarnomichel** [marcus-crane/october#56]
Hai!,

When trying to import I got the error: "There was a problem sending your highlights: parsing time "" as "2006-01-02T15:04:05.000": cannot parse "" as "2006".

Any idea what this might be about?

gr.

**Comment by marcus-crane** [comment]
Hey there,

This sounds quite familiar to #47 where purchased books are not currently supports (or rather, I haven't investigated how they appear in the Kobo database yet compared to sideloaded books)

It's a long weekend and now that I've got a bunch of internals moved around and deployed, I'll have a look at tackling these sync issues

Thanks for the heads up!

**Comment by marcus-crane** [comment]
Hi @jarnomichel,

I've just released `v1.1.1` which should handle cases where bookmarks are missing a creation date which is what was going on here.

Let me know if this solves the problem and feel free to re-open this issue if you continue to have trouble 🙂

**Comment by jarnomichel** [comment]
Great Marcus! Thanks. This fixed the issue. It works flawlessly now. Have a good weekend.
