### ISSUE TITLE
Double, weirdly titled books in list

### ISSUE THREAD

**Issue by timbruls** [marcus-crane/october#76]
When pushing highlights to readwise, I get double books, once with their title and the highlights and once with a string of characters for a title and the same highlights. (like : 7420a5e5-a596-41cc-9a4a-2fd2f0860dc4)

I can delete them in readwise but they show up again when I do another sync with October. Both bought books and documents I put on the reader directly are affected.

**Comment by marcus-crane** [comment]
Hi @timbruls,

Hmm, books with GUIDs are books that have been purchased from the Kobo store to my knowledge although I haven't done extensive testing with Kobo purchased titles.

Are you also using the official Kobo extension from Readwise as well? If you were, it seems reasonable to expect that you'd get duplicates (both via Readwise direct and from October) although I hadn't considered it before now so October should probably not try to process officially purchased books.

As for items you've put on the reader yourself, that doesn't sound quite right.

If you're on the latest version, would you be able to go to the Settings page, click the button to open your logs folder and email the last few logs (or if you know which one corresponds to your recent duplicate uploads) to `october@utf9k.net` and I'll see if I can spot anything that might give away the cause?

Thanks for the heads up

**Comment by timbruls** [comment]
I will test with the official extension turned off, I hadn't considered that. If it still persists, I will mail you the logs :)

**Comment by marcus-crane** [comment]
Hi @timbruls, I've just released [v1.3.2](https://github.com/marcus-crane/october/releases/tag/v1.3.2) which should ignore store-bought Kobo titles now. You'll need to delete any duplicate uploads one time however.

**Comment by marcus-crane** [comment]
Hey @timbruls, just letting you know that [v1.4.0](https://github.com/marcus-crane/october/releases/tag/v.1.4.0) has just released which has a toggle in Settings for opting into syncing store-purchased titles.

v1.3.2 also introduced some bugginess in querying so not all sideloaded titles may have synced with earlier versions.
