### ISSUE TITLE
The problem of duplicate book highlighting

### ISSUE THREAD

**Issue by Gikkingenhanaya** [marcus-crane/october#79]
I would like October to distinguish between the highlighting of books purchased from the bookstore and the highlighting of books uploaded to the kobo e-reader by myself. I only want to upload the highlighting of the books I have deposited in the e-reader through October, while the books purchased from the kobo bookstore are synced to readwise through the official kobo sync plugin of readwise

**Comment by marcus-crane** [comment]
Hi @Gikkingenhanaya,

Yep, this is indeed something that was overlooked at first and is mentioned in https://github.com/marcus-crane/october/issues/76

I plan to release a patch to fix this shortly but just haven't gotten around to it as I just recently got back from vacation 🙂 

Hopefully a version will be out in the next couple of days now that I have some free time

**Comment by Gikkingenhanaya** [comment]
Thank you for such a quick reply, looking forward to the new version!

**Comment by marcus-crane** [comment]
Hi @Gikkingenhanaya, I've just released [v1.3.2](https://github.com/marcus-crane/october/releases/tag/v1.3.2) which should ignore store-bought Kobo titles now. You'll need to delete any duplicate uploads one time however.
