### ISSUE TITLE
Create a Linux arm64 build

### ISSUE THREAD

**Issue by MugunthKumar** [marcus-crane/october#97]
The latest Linux build is compiled for amd64 architecture. Can you please create a release for arm64 version?

**Comment by marcus-crane** [comment]
Hi @MugunthKumar,

I'm currently on a short holiday but I can look into releasing an arm64 build when I get back in a few days. It should be pretty straight forward.

I also just noticed that the existing Linux build had failed to be released for v1.6.0 so I'll have a look at that too.

I don't have a Linux arm64 device myself but I should be able to emulate the experience by running Parallels on macOS Silicon.

Out of curiosity, what's the arm64 Linux device that you've got? I didn't realise there were many of them around 😮

**Comment by MugunthKumar** [comment]
raspberry-pi
It runs a custom version of Debian

**Comment by marcus-crane** [comment]
Heya, I'm properly back now and just catching up on things. I'll try and generate a build later today for you to try out. Going forward, I'll have to dig out a Raspberry Pi so I have something to test out new versions on, although they usually don't differ very much between platforms 🙂

**Comment by MugunthKumar** [comment]
Cool, I’m in AEST timezone and it’s morning 9 here. Ready to test today when you got a build out

**Comment by marcus-crane** [comment]
Ah ok, nice. I'm in New Zealand myself. I'm just at work at the moment but I'll have a look when I'm done for the day 🙂

**Comment by marcus-crane** [comment]
Unfortunately this is going to be a bit more involved to support. In short, October currently uses a database driver that requires [CGO](https://pkg.go.dev/cmd/cgo).

When October is built, Go has to compile the database driver for each architecture.

In the case of Linux arm, some of the instructions aren't able to be properly translated (or something along those lines) meaning it's not possible to compile a working version: https://github.com/marcus-crane/october/actions/runs/6768028504/job/18391678284#step:11:133

The way to support arm is to migrate October over to a CGO-less sqlite driver which is very much possible, although I would need to go through each platform to verify that they all work as expected.

Currently some of the release pipelines are broken as well so I need to spend some time fixing those up. I don't think I can build for macOS at the moment as some of the requirements for certification changed on Nov 1st and I haven't kept up to date.

I would like to support Linux for arm though so I'll post whenever I've got something to share

**Comment by marcus-crane** [comment]
In the meantime, I've dug a Raspberry Pi out of storage so I can manually create a version for you to test out.

It'd be good to know what type of Raspberry Pi because different ones have different architectures such as `armv7hf` which is different from `arm64` and so on.

**Comment by MugunthKumar** [comment]
Mine is a Raspberry Pi 4B I think it is armv7 (not sure)

**Comment by marcus-crane** [comment]
Hey @MugunthKumar,

I've generated a build using a Raspberry Pi 3 Model B v1.2 which uses the armhf architecture.

You can give it a try here: https://github.com/marcus-crane/october/releases/tag/v1.7.0-beta10

There isn't any way (to my knowledge) that I can automatically release for armhf automatically, as with all the other platforms so I'll have to think about whether it's something I'd officially support, as it means I'd have to manually build it each time, and it's a pretty slow process.

That said, I do releases rarely enough that it's probably not a huge deal and the surface area of October is still quite small.

If anything, I've got a Rasp Pi set up for it now anyway so I can script as much of the process as possible.

**Comment by MugunthKumar** [comment]
Should be  super late for you. Take some rest mate! I’ll have an update tomorrow

**Comment by MugunthKumar** [comment]
I could get the installer happy and the app itself installs. But the binary doesn’t run. It gives be a “no such file or directory” error. (The file is present though and the “x” attribute is set and I sudoed the call as well

**Comment by marcus-crane** [comment]
Ah interesting 🤔 Do you have any logs saved at `$HOME/.local/share/october/logs`? There may be none just yet if the app crashes quick enough. You shouldn't need sudo by any means though.

**Comment by MugunthKumar** [comment]
The architecture is not supported I believe. The binary itself doesn't start and there are no logs. I don't think emulated archictectures are supported on raspberrypi. I will see. But no stress. I will use my mac to use October. (I moved my calibre library to raspberrypi and so thought of moving this there as well)

**Comment by marcus-crane** [comment]
@MugunthKumar Hmm, can you run `uname -mp` on your Raspberry Pi just to confirm the architecture?

I guess the Raspberry Pi 4 really might be arm64 in which case I can probably compile a build using a VM on my Macbook for you to try

**Comment by MugunthKumar** [comment]
Yes it is arm64

**Comment by MugunthKumar** [comment]
Tried installing the 32-bit emulator. But the rabbit hole goes deeper (mostly because it is a UI-based app and has GLKit dependency). If compiling to 64-bit is not going to be easy, leave it as is. I will use my Mac.

On another note: If you can update the README file with build instructions, I will take a crack at it (when I have some time, probably during the year-end holidays and know a little bit of Golang.)

**Comment by marcus-crane** [comment]
Hey there,

Apologies for the delay! It's a bit of a weird week so I hadn't had much time at home to sit down.

I've uploaded a Linux arm64 build here: https://github.com/marcus-crane/october/releases/tag/v1.7.0-beta10

It looks like [Github will be finally adding support for arm64 runners](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) in Q1 2024 so I'm happy to manually create builds for each release until it can be automated

**Comment by MugunthKumar** [comment]
I’ll check this tomorrow and let you know. I think I had some issues last time I checked

**Comment by marcus-crane** [comment]
Just to follow up, I've officially released a version for Linux arm as part of the [latest release](https://github.com/marcus-crane/october/releases/tag/v1.8.0).

It seems to work within a Linux VM but I'd encourage you to open up a new issue with any particular issues you come across 🙂 

Thanks again for the request!
